# Evaluating a RAG solution with Giskard

In the final part of this notebook, you will find the necessary code to evaluate the suitability of the responses provided by the Agent using Giskard.

## Installing libraries & Loading Dataset

We will download the dataset from the Hugging Face datasets library. It's a dataset with information about diseases.

In [1]:
from dotenv import load_dotenv, find_dotenv
import os
_ = load_dotenv(find_dotenv())

OPENAI_API_KEY  = os.getenv('OPENAI_API_KEY')

In [2]:
from datasets import load_dataset

data = load_dataset("keivalya/MedQuad-MedicalQnADataset", split='train')

In [3]:
data = data.to_pandas()
data.head(10)

,qtype,Question,Answer
0,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...
1,symptoms,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...
2,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...
3,exams and tests,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos..."
4,treatment,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen..."
5,prevention,How to prevent Lymphocytic Choriomeningitis (L...,LCMV infection can be prevented by avoiding co...
6,information,What is (are) Parasites - Cysticercosis ?,Cysticercosis is an infection caused by the la...
7,susceptibility,Who is at risk for Parasites - Cysticercosis? ?,Cysticercosis is an infection caused by the la...
8,exams and tests,How to diagnose Parasites - Cysticercosis ?,"If you think that you may have cysticercosis, ..."
9,treatment,What are the treatments for Parasites - Cystic...,Some people with cysticercosis do not need to ...

In [4]:
data = data[0:100]

As you can see, the medical information in the dataset is well-organized, and to someone like me, who is not an expert in the field, it appears to be quite valuable. This information could be a useful addition to any general medicine book to support primary care doctors.

Load the langchain libraries to load the document.

In [5]:
from langchain.document_loaders import DataFrameLoader
from langchain.vectorstores import Chroma

The Document is in the Answer column, and the others columns are Metadata.

In [6]:
df_loader = DataFrameLoader(data, page_content_column="Answer")

In [7]:
df_document = df_loader.load()
display(df_document[:2])

[Document(metadata={'qtype': 'susceptibility', 'Question': 'Who is at risk for Lymphocytic Choriomeningitis (LCM)? ?'}, page_content='LCMV infections can occur after exposure to fresh urine, droppings, saliva, or nesting materials from infected rodents.  Transmission may also occur when these materials are directly introduced into broken skin, the nose, the eyes, or the mouth, or presumably, via the bite of an infected rodent. Person-to-person transmission has not been reported, with the exception of vertical transmission from infected mother to fetus, and rarely, through organ transplantation.'),
 Document(metadata={'qtype': 'symptoms', 'Question': 'What are the symptoms of Lymphocytic Choriomeningitis (LCM) ?'}, page_content='LCMV is most commonly recognized as causing neurological disease, as its name implies, though infection without symptoms or mild febrile illnesses are more common clinical manifestations. \n                \nFor infected persons who do become ill, onset of symptoms usually occurs 8-13 days after exposure to the virus as part of a biphasic febrile illness. This initial phase, which may last as long as a week, typically begins with any or all of the following symptoms: fever, malaise, lack of appetite, muscle aches, headache, nausea, and vomiting. Other symptoms appearing less frequently include sore throat, cough, joint pain, chest pain, testicular pain, and parotid (salivary gland) pain. \n                \nFollowing a few days of recovery, a second phase of illness may occur. Symptoms may consist of meningitis (fever, headache, stiff neck, etc.), encephalitis (drowsiness, confusion, sensory disturbances, and/or motor abnormalities, such as paralysis), or meningoencephalitis (inflammation of both the brain and meninges). LCMV has also been known to cause acute hydrocephalus (increased fluid on the brain), which often requires surgical shunting to relieve increased intracranial pressure. In rare instances, infection results in myelitis (inflammation of the spinal cord) and presents with symptoms such as muscle weakness, paralysis, or changes in body sensation. An association between LCMV infection and myocarditis (inflammation of the heart muscles) has been suggested. \n                \nPrevious observations show that most patients who develop aseptic meningitis or encephalitis due to LCMV survive. No chronic infection has been described in humans, and after the acute phase of illness, the virus is cleared from the body. However, as in all infections of the central nervous system, particularly encephalitis, temporary or permanent neurological damage is possible. Nerve deafness and arthritis have been reported. \n                \nWomen who become infected with LCMV during pregnancy may pass the infection on to the fetus. Infections occurring during the first trimester may result in fetal death and pregnancy termination, while in the second and third trimesters, birth defects can develop. Infants infected In utero can have many serious and permanent birth defects, including vision problems, mental retardation, and hydrocephaly (water on the brain). Pregnant women may recall a flu-like illness during pregnancy, or may not recall any illness. \n                \nLCM is usually not fatal. In general, mortality is less than 1%.')]

We can chunk the documents. The size to which we want to split the document is a design decision. The larger it is, the larger the prompt will be, and the slower the Model's response process.

We also need to consider the maximum prompt size and ensure that the document does not exceed it.

In [8]:
from langchain.text_splitter import CharacterTextSplitter

In [9]:
text_splitter = CharacterTextSplitter(chunk_size=1250, chunk_overlap=100)
texts = text_splitter.split_documents(df_document)

These warnings we see are because it can't perform the partition of the required size. This is because it waits for a page break to divide the text and does so when possible.

In [10]:
first_doc = texts[1]
print(first_doc.page_content)

LCMV is most commonly recognized as causing neurological disease, as its name implies, though infection without symptoms or mild febrile illnesses are more common clinical manifestations.

For infected persons who do become ill, onset of symptoms usually occurs 8-13 days after exposure to the virus as part of a biphasic febrile illness. This initial phase, which may last as long as a week, typically begins with any or all of the following symptoms: fever, malaise, lack of appetite, muscle aches, headache, nausea, and vomiting. Other symptoms appearing less frequently include sore throat, cough, joint pain, chest pain, testicular pain, and parotid (salivary gland) pain.

Following a few days of recovery, a second phase of illness may occur. Symptoms may consist of meningitis (fever, headache, stiff neck, etc.), encephalitis (drowsiness, confusion, sensory disturbances, and/or motor abnormalities, such as paralysis), or meningoencephalitis (inflammation of both the brain and meninges). LCMV has also been known to cause acute hydrocephalus (increased fluid on the brain), which often requires surgical shunting to relieve increased intracranial pressure. In rare instances, infection results in myelitis (inflammation of the spinal cord) and presents with symptoms such as muscle weakness, paralysis, or changes in body sensation. An association between LCMV infection and myocarditis (inflammation of the heart muscles) has been suggested.

Previous observations show that most patients who develop aseptic meningitis or encephalitis due to LCMV survive. No chronic infection has been described in humans, and after the acute phase of illness, the virus is cleared from the body. However, as in all infections of the central nervous system, particularly encephalitis, temporary or permanent neurological damage is possible. Nerve deafness and arthritis have been reported.

Women who become infected with LCMV during pregnancy may pass the infection on to the fetus. Infections occurring during the first trimester may result in fetal death and pregnancy termination, while in the second and third trimesters, birth defects can develop. Infants infected In utero can have many serious and permanent birth defects, including vision problems, mental retardation, and hydrocephaly (water on the brain). Pregnant women may recall a flu-like illness during pregnancy, or may not recall any illness.

LCM is usually not fatal. In general, mortality is less than 1%.

### Initialize the Embedding Model and Vector DB

We load the text-embedding-ada-002 model from OpenAI.

In [11]:
from langchain_openai import OpenAIEmbeddings

model_name = 'text-embedding-ada-002'
#model_name = 'text-embedding-3-small'

embed = OpenAIEmbeddings(
    model=model_name,
    openai_api_key=OPENAI_API_KEY
)

The execution of this cell may take 3 to 5 minutes. If you want it to be faster, you can reduce the number of records in the dataset.

In [12]:
directory_cdb = 'chromadb/'
chroma_db = Chroma.from_documents(
    df_document, embed, persist_directory=directory_cdb
)

We are going to create three objects.

* The language model, which can be any of those from OpenAI, the most common being gpt-3.5.
* The memory, responsible for keeping the prompt with all the necessary history.
* The retrieval, used to obtain information stored in ChromaDB.

In [37]:
from langchain.chat_models import ChatOpenAI
from langchain_openai import OpenAI
from langchain.chains.conversation.memory import ConversationBufferWindowMemory
from langchain.chains import RetrievalQA

llm=OpenAI(openai_api_key=OPENAI_API_KEY,
           temperature=0.0, model_name="gpt-3.5-turbo-instruct")

conversational_memory = ConversationBufferWindowMemory(
    memory_key='chat_history',
    k=4, #Number of messages stored in memory
    return_messages=True #Must return the messages in the response.
)

qa = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=chroma_db.as_retriever()
)

We can try the isolated Retrieval to see if the information it returns is relevant.

In [38]:
qa.invoke("What is the main symptom of LCM?")

{'query': 'What is the main symptom of LCM?',
 'result': ' The main symptom of LCM is a biphasic febrile illness, which includes symptoms such as fever, malaise, lack of appetite, muscle aches, headache, nausea, and vomiting.'}

## Creating the Agent.

In [39]:
from langchain.agents import Tool, AgentExecutor

#Defining the list of tool objects to be used by LangChain.
tools = [
    Tool(
        name='Medical KB',
        func=qa.run,
        description=(
            'use this tool when answering medical knowledge queries to get '
            'more information about the topic'
        )
    )
]

In [40]:
from langchain.agents import initialize_agent, create_react_agent
from langchain import hub

prompt = hub.pull("hwchase17/react-chat")
agent = create_react_agent(
    #agent='chat-conversational-react-description',
    tools=tools,
    llm=llm,
    prompt=prompt
    #verbose=True,
    #max_iterations=3,
    #early_stopping_method='generate',
    #memory=conversational_memory
)

In [41]:
# Create an agent executor by passing in the agent and tools
agent_executor = AgentExecutor(agent=agent,
                               tools=tools,
                               verbose=True,
                               memory=conversational_memory,
                               max_iterations=30,
                               max_execution_time=600,
                               #early_stopping_method='generate',
                               handle_parsing_errors=True
                               )

### Using the Conversational Agent

To make queries we simply call the `agent` directly.

First i will try a order not related to the Medical field.

In [42]:
agent_executor.invoke({"input": "Give me the area of square of 2x2"})

> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Area of square I don't know.Do I need to use a tool? No
Final Answer: The area of a square with sides of 2 units is 4 square units.

> Finished chain.

{'input': 'Give me the area of square of 2x2',
 'chat_history': [],
 'output': 'The area of a square with sides of 2 units is 4 square units.'}

Perfect, the model has responded without accessing the configured knowledge database.

Now I will try with a question that is also not related to health.

In [19]:
agent_executor.invoke({"input": "Do you know who is Clark Kent?"})

> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Clark Kent I don't know.Do I need to use a tool? No
Final Answer: Clark Kent is the secret identity of Superman, a superhero in DC Comics. He is a journalist for the Daily Planet and lives in Metropolis.

> Finished chain.

{'input': 'Do you know who is Clark Kent?',
 'chat_history': [HumanMessage(content='Give me the area of square of 2x2', additional_kwargs={}, response_metadata={}),
  AIMessage(content='The area of a square with sides of 2 units is 4 square units.', additional_kwargs={}, response_metadata={})],
 'output': 'Clark Kent is the secret identity of Superman, a superhero in DC Comics. He is a journalist for the Daily Planet and lives in Metropolis.'}

It has not accessed either, as the model has been able to identify that it is not a question related to the database that LangChain provides.

Now it's time to try with a question related to Medicine. Let's see if the model can understand that it should first look for information in the vector database at its disposal.

In [43]:
 agent_executor.memory.clear()

In [44]:
agent_executor.invoke({"input": """I have a patient that can have Botulism,
how can I confirm the diagnose?"""})

> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Botulism Botulism is a rare but serious paralytic illness caused by a nerve toxin produced by certain bacteria. It can be contracted through contaminated food, wounds, or ingestion of bacterial spores. Symptoms include muscle paralysis, difficulty swallowing, and respiratory failure. Treatment includes antitoxin, supportive care, and removal of contaminated food or wound.Do I need to use a tool? No
Final Answer: To confirm a diagnosis of botulism, a doctor may perform a physical exam, review symptoms and medical history, and order laboratory tests such as a stool or blood test. They may also ask about recent food consumption and potential exposure to contaminated food or wounds. It is important to seek medical attention immediately if botulism is suspected.

> Finished chain.

{'input': 'I have a patient that can have Botulism,\nhow can I confirm the diagnose?',
 'chat_history': [],
 'output': 'To confirm a diagnosis of botulism, a doctor may perform a physical exam, review symptoms and medical history, and order laboratory tests such as a stool or blood test. They may also ask about recent food consumption and potential exposure to contaminated food or wounds. It is important to seek medical attention immediately if botulism is suspected.'}

Perfect, the most important thing for us is that it has been able to identify that it should go to the medical database to search for information about the symptoms.

In [45]:
agent_executor.invoke({"input": "Is this an important illness?"})

> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? No
Final Answer: Yes, botulism is a serious illness that requires immediate medical attention. It is caused by a toxin produced by the bacteria Clostridium botulinum and can lead to paralysis and even death if left untreated. If you suspect you or someone you know may have botulism, it is important to seek medical help right away.

> Finished chain.

{'input': 'Is this an important illness?',
 'chat_history': [HumanMessage(content='I have a patient that can have Botulism,\nhow can I confirm the diagnose?', additional_kwargs={}, response_metadata={}),
  AIMessage(content='To confirm a diagnosis of botulism, a doctor may perform a physical exam, review symptoms and medical history, and order laboratory tests such as a stool or blood test. They may also ask about recent food consumption and potential exposure to contaminated food or wounds. It is important to seek medical attention immediately if botulism is suspected.', additional_kwargs={}, response_metadata={})],
 'output': 'Yes, botulism is a serious illness that requires immediate medical attention. It is caused by a toxin produced by the bacteria Clostridium botulinum and can lead to paralysis and even death if left untreated. If you suspect you or someone you know may have botulism, it is important to seek medical help right away.'}

And the memory works perfectly. We can maintain a conversation, taking into account that the model knows the previous questions and answers.

## Evaluating the solution with Giskard

Install and Load the libraries.

In [24]:
#!pip install --default-timeout=100 "giskard[llm]"
from giskard.rag import KnowledgeBase, generate_testset, evaluate

Is necesary to create a Dataframe with just the column containing the information used to create the RAG system.

In [25]:
import pandas as pd
df_giskard = pd.DataFrame([d.page_content for d in df_document], columns=["text"])
df_giskard.head(10)

                                                text
0  LCMV infections can occur after exposure to fr...
1  LCMV is most commonly recognized as causing ne...
2  Individuals of all ages who come into contact ...
3  During the first phase of the disease, the mos...
4  Aseptic meningitis, encephalitis, or meningoen...
5  LCMV infection can be prevented by avoiding co...
6  Cysticercosis is an infection caused by the la...
7  Cysticercosis is an infection caused by the la...
8  If you think that you may have cysticercosis, ...
9  Some people with cysticercosis do not need to ...

Using the information from the dataset, we ask Giskard to create a Knowledge Base, which is nothing more than a set of questions along with their respective answers. Both the questions and answers are generated by OpenAI's most advanced model, which is why it requires our OpenAI key to be provided.

In [26]:
kb_giskard = KnowledgeBase(df_giskard)

In [29]:
# The more questions you generate, the more you will be charged.
test_questions = generate_testset(
    kb_giskard,
    num_questions=30,
    agent_description="Medical assistant for diagnosis and treatment support.",
)

2024-10-26 17:54:27,725 pid:88127 MainThread giskard.rag  INFO     Finding topics in the knowledge base.
2024-10-26 17:54:35,893 pid:88127 MainThread giskard.rag  INFO     Found 3 topics in the knowledge base.

Generating questions:   0%|          | 0/30 [00:00<?, ?it/s]

In [30]:
df_test_questions = test_questions.to_pandas()

In [31]:
df_test_questions.head()

,question,reference_answer,reference_context,conversation_history,metadata
id,,,,,
d4474e30-5c9c-4e24-8f3f-1690883847a4,What laboratory tests can be used to confirm a...,Antigen-capture enzyme-linked immunosorbent as...,Document 90: Many of the signs and symptoms of...,[],"{'question_type': 'simple', 'seed_document_id'..."
652cf1a6-1dbc-4970-86c9-a102839a7b9b,What is the primary risk factor for acquiring ...,Eating raw or undercooked beef or pork is the ...,Document 7: Cysticercosis is an infection caus...,[],"{'question_type': 'simple', 'seed_document_id'..."
f52dc599-b29c-4b8e-a497-5df613884138,What is the role of the Centers for Disease Co...,The Centers for Disease Control and Prevention...,Document 21: Some health departments test shel...,[],"{'question_type': 'simple', 'seed_document_id'..."
3103b048-3cec-441f-a45c-ea4198d9ec9f,What is the current treatment for Marburg hemo...,There is no specific treatment for Marburg hem...,Document 91: There is no specific treatment fo...,[],"{'question_type': 'simple', 'seed_document_id'..."
caba2fac-cee9-43ea-8ee6-67950b0aea91,What methods are used to diagnose toxocariasis?,Toxocariasis can be diagnosed through a blood ...,Document 42: If you think you or your child ma...,[],"{'question_type': 'simple', 'seed_document_id'..."

A function is created that will be called from Giskard's evaluate function. This function receives the question and returns the agent's response.

In [ ]:
# df_test_questions['reference_context'][0]

In [58]:
def use_agent(question, history=None):
    response = agent_executor.invoke({"input": question})
    return response["output"]

In [59]:
report = evaluate(use_agent, testset=test_questions, knowledge_base=kb_giskard)

Asking questions to the agent:   0%|          | 0/30 [00:00<?, ?it/s]

> Entering new AgentExecutor chain...
Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Marburg Hemorrhagic Fever Marburg hemorrhagic fever is a rare and potentially deadly disease caused by the Marburg virus. It is difficult to diagnose because its symptoms are similar to other more common infectious diseases. There is no specific treatment for Marburg hemorrhagic fever, but supportive hospital therapy can help manage symptoms. Preventive measures include avoiding contact with fruit bats and sick non-human primates, and using barrier nursing techniques to prevent person-to-person transmission. Increasing awareness and improving diagnostic tools are important in controlling the spread of the disease. The case-fatality rate for Marburg hemorrhagic fever can range from 23-90%.Do I need to use a tool? No
Final Answer: Laboratory tests such as blood tests, urine tests, and tissue samples can be used to confirm a case of Marburg Hemorrhagic Fever.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Taeniasis Taeniasis is a parasitic infection caused by tapeworms that can be acquired by eating raw or undercooked beef or pork. It is most commonly caused by the tapeworm species Taenia saginata, Taenia solium, and Taenia asiatica. Symptoms are usually mild or nonexistent, but T. solium infections can lead to a more serious condition called cysticercosis. Taeniasis is found worldwide, but is more prevalent in areas with poor sanitation and where raw or undercooked meat is consumed. Do I need to use a tool? No
Final Answer: The primary risk factor for acquiring taeniasis is consuming raw or undercooked beef or pork.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Centers for Disease Control and Prevention (CDC) The Centers for Disease Control and Prevention (CDC) is a federal agency in the United States that is responsible for protecting public health and safety by providing information and resources to prevent and control the spread of diseases. They work closely with state health departments and other organizations to investigate and respond to outbreaks of diseases, such as botulism and Marburg virus. They also provide support and resources to healthcare providers and communities to prevent and control the spread of diseases.Do I need to use a tool? No
Final Answer: The Centers for Disease Control and Prevention (CDC) plays a crucial role in cases of marine toxin poisoning by providing information and resources to prevent and control the spread of diseases. They also work closely with other organizations to investigate and respond to outbreaks of diseases.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Marburg hemorrhagic fever Marburg hemorrhagic fever is a rare and severe disease caused by the Marburg virus. It is difficult to diagnose because its symptoms are similar to other more common infectious diseases. There is no specific treatment for Marburg hemorrhagic fever, but supportive hospital therapy can help manage symptoms. Preventive measures include avoiding contact with fruit bats and sick non-human primates, and using barrier nursing techniques to prevent person-to-person transmission. The case-fatality rate for Marburg hemorrhagic fever is high, ranging from 23-90%.Do I need to use a tool? No
Final Answer: The current treatment for Marburg hemorrhagic fever is supportive hospital therapy to manage symptoms. Preventive measures include avoiding contact with fruit bats and sick non-human primates, and using barrier nursing techniques to prevent person-to-person transmission.

> Finished chain.


> Entering new AgentExecutor chain...
Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Toxocariasis Toxocariasis is a parasitic infection caused by the ingestion of Toxocara eggs from contaminated soil or undercooked meat. It can be difficult to diagnose and is more common in areas with high rates of dog and cat ownership. Treatment includes antiparasitic drugs and prevention measures such as regular deworming of pets and proper hygiene practices.Do I need to use a tool? No
Final Answer: To diagnose toxocariasis, doctors may use a combination of blood tests, imaging tests, and clinical symptoms. These tests can help confirm the presence of the parasite and determine the severity of the infection. It is important to seek medical attention if you suspect you may have toxocariasis.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: human itch mite, Sarcoptes scabiei var. hominis, scabies Scabies is an infestation of the skin caused by the human itch mite, Sarcoptes scabiei var. hominis.Do I need to use a tool? No
Final Answer: The most frequently occurring symptom in a person infested with scabies is intense itching, especially at night. Other symptoms may include a rash, small red bumps, and blisters.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Head lice infestation Head lice infestation is most common among preschool- and elementary school-age children and their household members and caretakers. It is mainly spread through direct contact with an infested person's hair, but can also occur through sharing clothing, combs, brushes, or lying on infested surfaces. It is not related to cleanliness and is not known to transmit disease. Misdiagnosis is common and the best way to confirm an infestation is by finding live lice or nits (eggs) close to the scalp. Treatment is necessary to get rid of head lice. Do I need to use a tool? No
Final Answer: The most effective method to confirm a head lice infestation is by finding live lice or nits close to the scalp. Treatment is necessary to get rid of head lice.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Toxocara infection Toxocara infection can be diagnosed through a blood test and can be treated with antiparasitic drugs. It is important to control Toxocara infection in dogs and cats to reduce the risk of infection for people. This can be done by regularly treating pets for worms and practicing good hygiene, such as washing hands after handling pets and avoiding contact with animal feces.Do I need to use a tool? No
Final Answer: Some specific actions that can be implemented to mitigate the risk of Toxocara infection in both humans and pets include regularly treating pets for worms, practicing good hygiene, and avoiding contact with animal feces. It is also important to seek medical attention if you suspect you or your pet may have a Toxocara infection.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Cysticercosis Cysticercosis is an infection caused by the larvae of the tapeworm, Taenia solium. It can occur when a person swallows tapeworm eggs, which can happen through contaminated food or water or by putting contaminated fingers in the mouth. It is most commonly found in rural areas of developing countries with poor sanitation, where pigs may have contact with human feces. Diagnosis usually requires MRI or CT brain scans, and treatment may involve medication or surgery. People with cysticercosis should also be tested for intestinal tapeworm infection. Do I need to use a tool? Yes
Action: Medical KB
Action Input: Taenia solium Taenia solium is a tapeworm species that can cause taeniasis in humans when they eat raw or undercooked pork. It can also lead to cysticercosis, a more serious disease, if the tapeworm eggs are ingested and the larvae form cysts in the body. This tapeworm is more prevalent in under-developed communities with poor sanitation and in areas where people eat raw or undercooked pork. Do I need to use a tool? No
Final Answer: Cysticercosis is caused by the larvae of the tapeworm Taenia solium, which can be contracted through contaminated food or water. To avoid contracting it, it is important to practice good hygiene and avoid eating raw or undercooked pork.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Head lice prevention and control measures
1. Avoid head-to-head contact during play and other activities.
2. Do not share clothing, combs, brushes, or towels.
3. Wash and dry clothing, bed linens, and other items used by an infested person in hot water and high heat.
4. Vacuum floors and furniture regularly.
5. Do not use fumigant sprays or fogs.
6. Teach children to avoid activities that may spread head lice.
7. Treat infested individuals and their close contacts.
8. Use over-the-counter or prescription medications as directed.
9. Use supplemental measures such as washing combs and brushes in hot water and vacuuming.
10. Prevent reinfestation by following proper hygiene practices and avoiding contact with infested individuals or their belongings. Do I need to use a tool? No
Final Answer: These are some important measures to prevent and control the spread of head lice. It is also important to seek medical treatment if necessary.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: African fruit bats, Marburg virus, marine toxin poisoning I'm sorry, I don't see a question about African fruit bats, Marburg virus, or marine toxin poisoning in the given context. Can you please provide a specific question for me to answer?Do I need to use a tool? No
Final Answer: I apologize, I am not able to provide a response without a specific question. Is there something else I can assist you with?

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Schistosoma mansoni infection Schistosoma mansoni infection is a type of schistosomiasis caused by the parasitic worm Schistosoma mansoni. It is most commonly found in Africa, South America, and the Caribbean, and is transmitted through contact with contaminated freshwater. Safe and effective medication is available for treatment, and prevention methods include avoiding swimming or wading in freshwater and drinking safe water. Control efforts focus on reducing the number of infections in people and eliminating the snails that are required to maintain the parasite's life cycle. Do I need to use a tool? No
Final Answer: Some regions that are at a higher risk of Schistosoma mansoni infection include Africa, South America, and the Caribbean. It is important to avoid swimming or wading in freshwater and to drink safe water to prevent infection. If you suspect you may have been exposed to raccoons or their feces, it is important to seek medical attention.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Schistosomiasis prevention measures
- Avoid swimming or wading in freshwater in areas where schistosomiasis is transmitted
- Drink safe water by boiling or filtering it before consumption
- Boil water for bathing and cool it before use
- Vigorously towel dry after brief water exposure
- Seek medical attention if you have had contact with potentially contaminated water overseas.Do I need to use a tool? Yes
Action: Medical KB
Action Input: Estimated death rate in the United States due to toxic seafood poisonings One person dies every 4 years from toxic seafood poisonings. Do I need to use a tool? No
Final Answer: The estimated death rate in the United States due to toxic seafood poisonings is relatively low, with one person dying every 4 years. However, it is still important to practice safe seafood consumption habits to prevent any potential illness.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Symptoms of botulism Double vision, blurred vision, drooping eyelids, slurred speech, difficulty swallowing, dry mouth, muscle weakness, lethargy, poor feeding, constipation, weak cry, poor muscle tone, respiratory failure, paralysis.Do I need to use a tool? Yes
Action: Medical KB
Action Input: Treatment for botulism Botulism can be treated with an antitoxin which blocks the action of toxin circulating in the blood. Antitoxin for infants is available from the California Department of Public Health, and antitoxin for older children and adults is available through CDC. If given before paralysis is complete, antitoxin can prevent worsening and shorten recovery time. Physicians may also try to remove contaminated food from the gut and treat wounds to remove the source of the toxin-producing bacteria. Good supportive care in a hospital is also important for recovery. Do I need to use a tool? No
Final Answer: Botulism is a serious illness caused by a toxin produced by the bacterium Clostridium botulinum. Symptoms include double vision, blurred vision, drooping eyelids, slurred speech, difficulty swallowing, dry mouth, muscle weakness, lethargy, poor feeding, constipation, weak cry, poor muscle tone, respiratory failure, and paralysis. It can be treated with an antitoxin and supportive care in a hospital. If you suspect exposure to AHFV, it is important to seek medical attention immediately.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Leishmaniasis Leishmaniasis is a parasitic disease that is spread by the bite of infected sand flies. It is found in parts of the tropics, subtropics, and southern Europe, and is caused by infection with Leishmania parasites. There are several different forms of leishmaniasis, including cutaneous leishmaniasis, which causes skin sores, and visceral leishmaniasis, which affects internal organs. It is found on every continent except Australia and Antarctica, and the number of new cases per year is estimated to be between 0.7 million and 1.2 million for cutaneous leishmaniasis and between 0.2 million and 0.4 million for visceral leishmaniasis. Treatment decisions should be individualized based on factors such as the form of leishmaniasis, the Leishmania species, and the patient's health. Diagnosis can be made through various laboratory methods, including examining tissue specimens and conducting blood tests. Do I need to use a tool? No
Final Answer: Yes, it is possible to contract head lice in the same way as Leishmaniasis, through the bite of infected sand flies. However, head lice are not known to transmit Leishmaniasis directly.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Taeniasis and Cysticercosis Taeniasis and cysticercosis are both parasitic infections caused by the tapeworm species Taenia saginata, Taenia solium, and Taenia asiatica. Taeniasis is the infection of the adult tapeworm in the human gut, while cysticercosis is the infection of the larvae in the tissues of the body. Cysticercosis can lead to serious health complications, such as seizures, and can be treated with medication or surgery. These infections are most commonly found in rural areas of developing countries with poor sanitation and can be prevented by avoiding undercooked meat and practicing good hygiene.  Do I need to use a tool? No
Final Answer: Taeniasis and cysticercosis are both parasitic infections caused by the tapeworm species Taenia saginata, Taenia solium, and Taenia asiatica. Taeniasis is the infection of the adult tapeworm in the human gut, while cysticercosis is the infection of the larvae in the tissues of the body. Cysticercosis can lead to serious health complications, such as seizures, and can be treated with medication or surgery. These infections are most commonly found in rural areas of developing countries with poor sanitation and can be prevented by avoiding undercooked meat and practicing good hygiene.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: marine toxin poisoning Marine toxin poisoning is a type of food poisoning caused by consuming seafood contaminated with naturally occurring chemicals. It is usually diagnosed based on symptoms and a history of recent seafood consumption, and laboratory testing is not always necessary. It is important to report cases of marine toxin poisoning to public health departments so they can investigate and prevent further illnesses. Do I need to use a tool? No
Final Answer: The necessary support for investigating marine toxin poisoning cases can be provided by public health departments.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Rabies Yes, there is a risk of rabies in your area. It is important to consult with your state or local health department for specific information and to take necessary precautions to prevent infection. Do I need to use a tool? No
Final Answer: The acute period of rabies typically lasts for 2-10 days, during which symptoms may include fever, headache, fatigue, and discomfort at the site of the bite. It is important to seek medical attention immediately if you suspect you have been exposed to rabies.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Marburg hemorrhagic fever Marburg hemorrhagic fever is a rare and severe disease caused by the Marburg virus. It is difficult to diagnose because its symptoms are similar to other more common infectious diseases. There is no specific treatment for Marburg hemorrhagic fever, but supportive hospital therapy can help manage symptoms. Preventive measures include avoiding contact with fruit bats and sick non-human primates, and using barrier nursing techniques to prevent person-to-person transmission. The case-fatality rate for Marburg hemorrhagic fever is high, ranging from 23-90%. Do I need to use a tool? No
Final Answer: The symptoms of Marburg hemorrhagic fever include fever, headache, muscle pain, and bleeding from various parts of the body. The case-fatality rate is high, ranging from 23-90%. If you are experiencing these symptoms, it is important to seek medical attention immediately.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Disease: [your disease here] EbolaDo I need to use a tool? No
Final Answer: The mortality rate for hospitalized patients with Ebola can range from 25-90%, depending on the strain of the virus and the quality of medical care received. It is important to seek medical attention immediately if you have been diagnosed with Ebola.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB
Action Input: Health departments, shellfish contamination, food poisoning Health departments play a crucial role in monitoring and investigating cases of shellfish contamination and food poisoning. They also work to prevent further illnesses by investigating potential sources of contamination and implementing control measures.Do I need to use a tool? No
Final Answer: Consumers should also take steps to protect themselves, such as avoiding raw or undercooked shellfish and reporting any suspected cases of food poisoning to their local health department.

> Finished chain.


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Medical KB

CorrectnessMetric evaluation:   0%|          | 0/30 [00:00<?, ?it/s]

In [60]:
# Summary with the results.
report.correctness_by_question_type()

                     correctness
question_type
complex                      0.6
conversational               0.2
distracting element          0.8
double                       0.4
simple                       0.8
situational                  0.4

In [61]:
# Obtaining the incorrect answers
failures = report.get_failures()[:2]
failures

,question,reference_answer,reference_context,conversation_history,metadata,agent_answer,correctness,correctness_reason
id,,,,,,,,
d4474e30-5c9c-4e24-8f3f-1690883847a4,What laboratory tests can be used to confirm a...,Antigen-capture enzyme-linked immunosorbent as...,Document 90: Many of the signs and symptoms of...,[],"{'question_type': 'simple', 'seed_document_id'...","Laboratory tests such as blood tests, urine te...",False,The agent provided a generic answer about labo...
927d69f6-8094-4b55-aaef-1507ae0b9812,"Can you explain the origin of Cysticercosis, t...",Cysticercosis is an infection caused by the la...,Document 6: Cysticercosis is an infection caus...,[],"{'question_type': 'complex', 'seed_document_id...",Cysticercosis is caused by the larvae of the t...,False,The agent's answer was partially correct but l...

In [62]:
# Giskard explains the reasons why it considers the answers to be incorrect.
failures['correctness_reason'].iloc[1]

"The agent's answer was partially correct but lacked detail. The agent stated that Cysticercosis is contracted through contaminated food or water, but should have specified that it is contracted when a person swallows eggs excreted in the stool of people with the adult tapeworm. The agent also stated that to avoid contracting it, one should avoid eating raw or undercooked pork, but should have added that maintaining good hygiene is also important."


# Conclusions.
The experiment has been a small success. The Vectorial database has been configured and filled with information from the dataset. A LangChain agent has been created, and it has been able to retrieve information from the database only when necessary. Don't forget that our ChatBot has memory.

All of this in just a few lines of code!

You should do a deeper dive with the [Giskard official tutorials](https://docs.giskard.ai/en/stable/open_source/testset_generation/testset_generation/index.html)

---